# Generated by Django 4.2.1 on 2023-06-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Streamings2023', '0002_alter_accountinvoice_account_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinvoice',
            name='account_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
